[package]
name = "_1200_dollars_per_hour"
version = "0.1.3"
license = "MIT"

[addresses]
_1200_dollars_per_hour ="_"
std="0x1"
aptos_framework="0x1"
aptos_std="0x1"
aptos_token="0x3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="main" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="main" }
